integration:
  platform:
    x-space-id:
    model-list-url:
    agent-list-url:
    agent-detail-url:
    agent-bundle-list-url:
    agent-chat-url:
    trust-all-ssl: true
    connect-timeout-ms: 5000
    read-timeout-ms: 60000
    iam:
      url:
      authorization:
