integration:
  platform:
    x-space-id:
    model-list-url:
    agent-list-url:
    agent-detail-url:
    # 模型对话接口，支持使用 {modelId} 作为路径占位符。
    model-chat-url:
    trust-all-ssl: true
    connect-timeout-ms: 5000
    read-timeout-ms: 60000
    iam:
      enabled: false
      url:
      authorization:
    login:
      url:
      login-account:
      uid:
      password:
      lang:
      remember-account-name: true
      app-id:
      encrypted-password-switch:
