agentnexus:
  master:
    service:
      url:

integration:
  platform:
    agent-chat-url:
    sso-cookie-renewal-url:
    trust-all-ssl: true
    connect-timeout-ms: 500000
    read-timeout-ms: 6000000
    iam:
      url:
      authorization:
